import { EvaluationItem, ReviewQueueItem, ActivityItem, NotificationItem, UserProfile } from '../types'

export const MOCK_USER: UserProfile = {
  id: 'usr_evaluator_9901',
  name: 'Dr. Sarah Jenkins',
  email: 's.jenkins@stanford.edu',
  role: 'Lead Evaluator & Professor',
  department: 'Computer Science Department',
  institution: 'Stanford University',
  avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=200',
}

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'Batch Grading Complete',
    message: 'CS106B Midterm Evaluation completed for 142 submissions.',
    timestamp: '10 mins ago',
    read: false,
    type: 'success',
  },
  {
    id: 'notif-2',
    title: 'Manual Review Required',
    message: 'Submission UUID-8891 requires human review (confidence 71%).',
    timestamp: '45 mins ago',
    read: false,
    type: 'warning',
  },
  {
    id: 'notif-3',
    title: 'Privacy Compliance Audit Passed',
    message: 'All student submissions anonymized with zero PII retention.',
    timestamp: '2 hours ago',
    read: true,
    type: 'info',
  },
  {
    id: 'notif-4',
    title: 'Backend API Connected',
    message: 'Smart Grade Assistant API health status check returned OK.',
    timestamp: '5 hours ago',
    read: true,
    type: 'info',
  },
]

export const MOCK_EVALUATIONS: EvaluationItem[] = [
  {
    id: 'eval-9041',
    anonymousStudentId: '8f9a2b1c-9901-4c12-b12e-89a1023d881a',
    courseCode: 'CS106B',
    courseName: 'Programming Abstractions',
    submittedAt: '2026-09-04 13:45',
    confidenceScore: 98,
    score: 94,
    status: 'auto_graded',
  },
  {
    id: 'eval-9042',
    anonymousStudentId: '3c12f90a-112e-4b99-a881-229f01889c10',
    courseCode: 'CS182',
    courseName: 'Ethics, Public Policy & AI',
    submittedAt: '2026-09-04 13:20',
    confidenceScore: 74,
    score: 82,
    status: 'pending_review',
    flaggedReason: 'Ambiguous diagram formatting requires manual verification',
  },
  {
    id: 'eval-9043',
    anonymousStudentId: '1a90c44b-771f-490d-90c1-331289190abf',
    courseCode: 'MATH51',
    courseName: 'Linear Algebra & Multivariable Calculus',
    submittedAt: '2026-09-04 12:50',
    confidenceScore: 99,
    score: 98,
    status: 'finalized',
    evaluatorName: 'Dr. Sarah Jenkins',
  },
  {
    id: 'eval-9044',
    anonymousStudentId: '90b1c22d-881a-4c12-9900-112233445566',
    courseCode: 'PHYS41',
    courseName: 'Mechanics & Thermodynamics',
    submittedAt: '2026-09-04 11:30',
    confidenceScore: 68,
    score: 76,
    status: 'manual_review',
    flaggedReason: 'Handwritten notation low confidence threshold',
  },
  {
    id: 'eval-9045',
    anonymousStudentId: '77221199-aabb-ccdd-eeff-001122334455',
    courseCode: 'CS106B',
    courseName: 'Programming Abstractions',
    submittedAt: '2026-09-04 10:15',
    confidenceScore: 96,
    score: 91,
    status: 'auto_graded',
  },
  {
    id: 'eval-9046',
    anonymousStudentId: '44556677-8899-00aa-bbcc-ddeeff001122',
    courseCode: 'EE108',
    courseName: 'Digital Systems Design',
    submittedAt: '2026-09-04 09:40',
    confidenceScore: 95,
    score: 89,
    status: 'finalized',
    evaluatorName: 'Prof. Marcus Chen',
  },
]

export const MOCK_REVIEWS: ReviewQueueItem[] = [
  {
    id: 'rev-101',
    anonymousStudentId: '3c12f90a-112e-4b99-a881-229f01889c10',
    courseCode: 'CS182',
    assignmentTitle: 'Midterm Essay - Algorithmic Fairness',
    submittedAt: '2026-09-04 13:20',
    confidenceScore: 74,
    suggestedScore: 82,
    priority: 'high',
    flagReason: 'Margin notes exceed standard bounding box',
  },
  {
    id: 'rev-102',
    anonymousStudentId: '90b1c22d-881a-4c12-9900-112233445566',
    courseCode: 'PHYS41',
    assignmentTitle: 'Lab Report 4 - Wave Mechanics',
    submittedAt: '2026-09-04 11:30',
    confidenceScore: 68,
    suggestedScore: 76,
    priority: 'medium',
    flagReason: 'Vector diagram parsing requires instructor check',
  },
  {
    id: 'rev-103',
    anonymousStudentId: 'bb112233-4455-6677-8899-00aabbccdde',
    courseCode: 'BIO81',
    assignmentTitle: 'Genetics Problem Set 2',
    submittedAt: '2026-09-04 08:15',
    confidenceScore: 79,
    suggestedScore: 88,
    priority: 'low',
    flagReason: 'Alternative proof method detected',
  },
]

export const MOCK_ACTIVITIES: ActivityItem[] = [
  {
    id: 'act-1',
    timestamp: '12 mins ago',
    type: 'evaluation_completed',
    title: 'Batch CS106B Graded',
    description: '142 submissions processed with 96.4% confidence average.',
    anonymousStudentId: '8f9a2b1c-9901-4c12-b12e-89a1023d881a',
  },
  {
    id: 'act-2',
    timestamp: '42 mins ago',
    type: 'manual_review_needed',
    title: 'Manual Verification Queued',
    description: 'Submission flagged due to non-standard diagram notation.',
    anonymousStudentId: '3c12f90a-112e-4b99-a881-229f01889c10',
  },
  {
    id: 'act-3',
    timestamp: '2 hours ago',
    type: 'report_generated',
    title: 'Departmental Report Exported',
    description: 'Stanford CS Midterm Grade Distribution PDF generated.',
  },
  {
    id: 'act-4',
    timestamp: '4 hours ago',
    type: 'system_alert',
    title: 'Privacy Anonymizer Sync',
    description: 'Zero PII integrity verified across 1,250 student records.',
  },
]
